<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Create Tipraspuns' => 'Adaugă',
  'Delete Tipraspuns' => 'Șterge',
  'List Subdiv' => '',
  'Manage Tipraspuns' => 'Administrare',
  'Tipraspuns' => 'Tipurile de răspunsuri',
  'Update Tipraspuns' => 'Modifică',
  'View Tipraspuns' => 'Afișează',
  'View Users' => '',
  'Zona Administrativa' => '',
  'Advanced Search' => 'Căutare avansată',
  'Create' => 'Adăugare',
  'Create Responsabil' => 'Adaugă responsabil',
  'Create Subdiv' => 'Adaugă subdiviziune',
  'Create User' => 'Adaugă utilizator',
  'Create Users' => 'Adaugă utilizator',
  'Delete Responsabil' => 'Șterge responsabil',
  'Delete Subdiv' => 'Șterge subdiviziunea',
  'Delete Users' => 'Șterge utilizator',
  'Fields with <span class="required">*</span> are required.' => 'Cîmpurile cu <span class="required">*</span> sunt obligatorii pentru îndeplinire.',
  'Home' => 'Pagina principală',
  'Login' => 'Logare',
  'Logout' => 'Ieșire',
  'Manage' => 'Administrare',
  'Manage Responsabil' => 'Administrează responsabilii',
  'Manage Responsabils' => 'Administrarea responsabililor',
  'Manage Subdiv' => 'Administrează subdiviziunile',
  'Manage Subdivs' => 'Administrarea subdiviziunilor',
  'Manage Users' => 'Administrează utilizatorii',
  'Responsabils' => 'Responsabili',
  'Subdivs' => 'Subdiviziuni',
  'Update' => 'Modificare',
  'Update Responsabil' => 'Modifică responsabilul',
  'Update Subdiv' => 'Modifică subdiviziunea',
  'Update User' => 'Modifică utilizator',
  'Update Users' => 'Modifică utilizator',
  'Users' => 'Utilizatori',
  'View Responsabil' => 'Vizualizează responsabilul',
  'View Subdiv' => 'Vizualizează',
  'View User' => 'Vizualizează',
);
